## DATE APPROACHES

## Two approaches to files
    1. when it is in the same  directory WITH THE NOTEBOOK

In [ ]:
import pandas as pd
student_data=pd.read_csv("studentsperformance.csv")
student_data

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [2]:
student_data.shape

(1000, 8)

##  QN 1 Hw many female students scored 80 and above in maths

In [17]:
female_students_80_and_above_math = student_data[(student_data['gender'] == 'female') & (student_data['math score'] >= 80)],
female_students_80_and_above_math

(     gender race/ethnicity parental level of education     lunch  \
 2    female        group B             master's degree  standard
 6    female        group B                some college  standard
 56   female        group E          associate's degree  standard
 102  female        group D          associate's degree  standard
 106  female        group D             master's degree  standard
 ..      ...            ...                         ...       ...
 957  female        group D             master's degree  standard
 962  female        group E          associate's degree  standard
 970  female        group D           bachelor's degree  standard
 979  female        group C          associate's degree  standard
 995  female        group E             master's degree  standard

     test preparation course  math score  reading score  writing score
 2                      none          90             95             93
 6                 completed          88             95             92
 56                completed          82             85             86
 102                    none          85             91             89
 106                    none          87            100            100
 ..                      ...         ...            ...            ...
 957                    none          92            100            100
 962                    none         100            100            100
 970                    none          89            100            100
 979                    none          91             95             94
 995               completed          88             99             95

 [74 rows x 8 columns],)

In [18]:
count = len(female_students_80_and_above_math[0])
count

74

## qn2

In [19]:
completed_students = student_data[student_data['test preparation course'] == 'completed']
completed_students

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
1,female,group C,some college,standard,completed,69,90,88
6,female,group B,some college,standard,completed,88,95,92
8,male,group D,high school,free/reduced,completed,64,64,67
13,male,group A,some college,standard,completed,78,72,70
18,male,group C,master's degree,free/reduced,completed,46,42,46
...,...,...,...,...,...,...,...,...
990,male,group E,high school,free/reduced,completed,86,81,75
991,female,group B,some high school,standard,completed,65,82,78
995,female,group E,master's degree,standard,completed,88,99,95
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77

In [20]:
mean_read_completed_students = completed_students['reading score'].mean()
mean_read_completed_students

np.float64(73.89385474860335)

## QN3

In [21]:
student_data["writing score"].max() - student_data["writing score"].min()

np.int64(90)

In [22]:
male_students = student_data[student_data['gender'] == 'male']['reading score'].std()
male_students

np.float64(13.931832063729495)

In [23]:
total_students = student_data['math score'] + student_data['reading score'] + student_data['writing score']
total_students.sum()

np.int64(203312)

In [25]:
tatol_score=student_data["math score"]+ student_data["reading score"]+ student_data["writing score"]
tatol_score.sum()

np.int64(203312)

In [33]:
tatol_score.mean()

np.float64(203.312)

In [30]:
import numpy as np

In [28]:
ninth_th = np.percentile([tatol_score],90)
ninth_th

np.float64(258.0)

In [37]:
IQR = tatol_score.quantile(0.75) - tatol_score.quantile(0.25)
IQR

np.float64(58.0)

## QN 1:  HW MANY FEMALE STUDENTS  SCORED 80 AND ABOVE IN MATHS 
## QN2:MEAN FOR......
## QN3: WHAT IS THE MEAN READING SCORE WHO COMPELET THE TEST PRIPERATION SCORE WAT IS THE RANGE FROM  THE WRITTING SCORE 
FIND THE STANDED VIR OF THE READING  SCORE 
 COMPUTER THE COMPETINIG SCORE AND FIND 
 A; AVERAGE OF TE TOTAL SCORE 
 B: THE 90TH PERCENTAILE 
 C:FIND THE INTER QUTILE RANGE